services:
  caster:
    build:
      context: .
      target: runner
    volumes:
      - ./:/work
      # web cam
      - /dev/video0:/dev/video0
    working_dir: /work
    command: bash
    environment:
      TZ: Asia/Tokyo
    # Allow X server connection
    network_mode: "host"
    # for /dev mount
    privileged: true
